name: Build SmbiosSpoofer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y uuid-dev iasl nasm
    - name: Setup EDK2
      run: |
        git clone --depth 1 https://github.com/tianocore/edk2.git
        cd edk2
        git submodule update --init --recursive
        make -C BaseTools
    - name: Build
      run: |
        export WORKSPACE=$GITHUB_WORKSPACE/edk2
        export EDK_TOOLS_PATH=$WORKSPACE/BaseTools
        export PACKAGES_PATH=$WORKSPACE:$GITHUB_WORKSPACE
        export PATH=$WORKSPACE/BaseTools/BinWrappers/PosixLike:$PATH
        cd $WORKSPACE
        build -a X64 -b RELEASE -t GCC -p SmbiosChanger/SmbiosSpooferV2.dsc
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmbiosSpooferV4
        path: Build/SmbiosSpooferV2/**/*.efi
